version: 2
updates:
  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    groups:
      actions-dependencies:
        patterns:
          - "*"

  # Maintain Python (pip) dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    groups:
      python-dependencies:
        patterns:
          - "*"
